// <auto-generated />
namespace TokenAuth.API.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class adding_client_table : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(adding_client_table));
        
        string IMigrationMetadata.Id
        {
            get { return "202312151549426_adding_client_table"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
